/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pratikum19062025;

/**
 *
 * @author user
 */
public class MenuMakanann extends javax.swing.JFrame {

    /**
     * Creates new form MenuMakanann
     */
    private MenuUtama utama;
    public MenuMakanann() {
        initComponents();
    }
    public MenuMakanann(MenuUtama utama){
        this.utama=utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkNasgor = new javax.swing.JCheckBox();
        chkMie = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        chkSoto = new javax.swing.JCheckBox();
        txtNasgor = new javax.swing.JTextField();
        txtMie = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtSoto = new javax.swing.JTextField();
        cbNasgor = new javax.swing.JComboBox<>();
        cbMie = new javax.swing.JComboBox<>();
        cbSate = new javax.swing.JComboBox<>();
        cbSoto = new javax.swing.JComboBox<>();
        txtTotNasgor = new javax.swing.JTextField();
        txtTotMie = new javax.swing.JTextField();
        txtTotSate = new javax.swing.JTextField();
        txtTotSoto = new javax.swing.JTextField();
        btnTotMakanan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DAFTAR MENU MAKANAN");

        chkNasgor.setText("Nasi Goreng");
        chkNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasgorActionPerformed(evt);
            }
        });

        chkMie.setText("Mie Goreng");
        chkMie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieActionPerformed(evt);
            }
        });

        chkSate.setText("Sate Ayam");
        chkSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateActionPerformed(evt);
            }
        });

        chkSoto.setText("Soto");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        txtNasgor.setText("0");

        txtMie.setText("0");

        txtSate.setText("0");

        txtSoto.setText("0");

        cbNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNasgorActionPerformed(evt);
            }
        });

        cbMie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMieActionPerformed(evt);
            }
        });

        cbSate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSateActionPerformed(evt);
            }
        });

        cbSoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSotoActionPerformed(evt);
            }
        });

        txtTotNasgor.setText("0");

        txtTotMie.setText("0");

        txtTotSate.setText("0");

        txtTotSoto.setText("0");

        btnTotMakanan.setText("Total");
        btnTotMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotMakananActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtTotal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(chkNasgor)
                                        .addGap(66, 66, 66))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkMie)
                                        .addGap(72, 72, 72)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chkSate)
                                    .addGap(76, 76, 76)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkSoto)
                                    .addComponent(btnReset))
                                .addGap(92, 92, 92)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSoto, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(txtSate)
                            .addComponent(txtMie)
                            .addComponent(txtNasgor))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNasgor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(btnTotMakanan)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotNasgor, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(txtTotMie)
                    .addComponent(txtTotSate)
                    .addComponent(txtTotSoto)
                    .addComponent(txtTotal))
                .addGap(0, 176, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNasgor)
                    .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMie)
                    .addComponent(txtMie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotMie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSate)
                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoto)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotMakanan)
                    .addComponent(btnReset)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMakanann(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void chkNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasgorActionPerformed
        
        txtNasgor.setText("15000");
    }//GEN-LAST:event_chkNasgorActionPerformed

    private void chkMieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieActionPerformed
        txtMie.setText("10000");
    }//GEN-LAST:event_chkMieActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        txtSate.setText("18000");
    }//GEN-LAST:event_chkSateActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
       txtSoto.setText("20000");
    }//GEN-LAST:event_chkSotoActionPerformed

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasgorActionPerformed
        int jumlah = (int) cbNasgor.getSelectedIndex();
        double harga = Double.parseDouble(txtNasgor.getText());
        double total = jumlah * harga;
        txtTotNasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasgorActionPerformed

    private void cbMieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieActionPerformed
        int jumlah = (int) cbMie.getSelectedIndex();
        double harga = Double.parseDouble(txtMie.getText());
        double total = jumlah * harga;
        txtTotMie.setText(Double.toString(total));
    }//GEN-LAST:event_cbMieActionPerformed

    private void cbSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSateActionPerformed
        int jumlah = (int) cbSate.getSelectedIndex();
        double harga = Double.parseDouble(txtSate.getText());
        double total = jumlah*harga;
        txtTotSate.setText(Double.toString(total));
    }//GEN-LAST:event_cbSateActionPerformed

    private void cbSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSotoActionPerformed
       int jumlah = (int) cbSoto.getSelectedIndex();
       double harga = Double.parseDouble(txtSoto.getText());
       double total = jumlah * harga;
       txtTotSoto.setText(Double.toString(total));
    }//GEN-LAST:event_cbSotoActionPerformed

    private void btnTotMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotMakananActionPerformed
        double nasgor = Double.parseDouble(txtTotNasgor.getText());
        double mie = Double.parseDouble(txtTotMie.getText());
        double sate = Double.parseDouble(txtTotSate.getText());
        double soto = Double.parseDouble(txtTotSoto.getText());
        double total = nasgor + mie + sate + soto;
        txtTotal.setText(Double.toString(total));
                
    }//GEN-LAST:event_btnTotMakananActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNasgor.setText("0");
        txtMie.setText("0");
        txtSate.setText("0");
        txtSoto.setText("0");
        txtTotal.setText("0");
        cbNasgor.setSelectedIndex(0);
        cbMie.setSelectedIndex(0);
        cbSate.setSelectedIndex(0);
        cbSoto.setSelectedIndex(0);
        chkNasgor.setSelected(false);
        chkMie.setSelected(false);
        chkSate.setSelected(false);
        chkSoto.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMakanann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMakanann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMakanann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMakanann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMakanann().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotMakanan;
    private javax.swing.JComboBox<String> cbMie;
    private javax.swing.JComboBox<String> cbNasgor;
    private javax.swing.JComboBox<String> cbSate;
    private javax.swing.JComboBox<String> cbSoto;
    private javax.swing.JCheckBox chkMie;
    private javax.swing.JCheckBox chkNasgor;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMie;
    private javax.swing.JTextField txtNasgor;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    private javax.swing.JTextField txtTotMie;
    private javax.swing.JTextField txtTotNasgor;
    private javax.swing.JTextField txtTotSate;
    private javax.swing.JTextField txtTotSoto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
