/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pratikum19062025;

/**
 *
 * @author user
 */
public class MenuMinuman extends javax.swing.JFrame {

    /** Creates new form MenuMinuman */
    private MenuUtama utama;
    public MenuMinuman() {
        initComponents();
    }
    public MenuMinuman(MenuUtama utama){
        this.utama=utama;
         initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTeh = new javax.swing.JComboBox<>();
        cbSusu = new javax.swing.JComboBox<>();
        chkTeh = new javax.swing.JCheckBox();
        chkSusu = new javax.swing.JCheckBox();
        chkFanta = new javax.swing.JCheckBox();
        chkJeruk = new javax.swing.JCheckBox();
        txtTeh = new javax.swing.JTextField();
        txtSusu = new javax.swing.JTextField();
        txtFanta = new javax.swing.JTextField();
        txtJeruk = new javax.swing.JTextField();
        cbFanta = new javax.swing.JComboBox<>();
        cbJeruk = new javax.swing.JComboBox<>();
        txtTotTeh = new javax.swing.JTextField();
        txtTotSusu = new javax.swing.JTextField();
        txtTotFanta = new javax.swing.JTextField();
        txtTotJeruk = new javax.swing.JTextField();
        btnTotalMakanan = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnMenuUtama = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DAFTAR MENU MINUMAN");

        cbTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehActionPerformed(evt);
            }
        });

        cbSusu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSusuActionPerformed(evt);
            }
        });

        chkTeh.setText("Es teh");
        chkTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTehActionPerformed(evt);
            }
        });

        chkSusu.setText("Susu Dingin");
        chkSusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSusuActionPerformed(evt);
            }
        });

        chkFanta.setText("Fanta");
        chkFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFantaActionPerformed(evt);
            }
        });

        chkJeruk.setText("Jus Jeruk");
        chkJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJerukActionPerformed(evt);
            }
        });

        txtTeh.setText("0");

        txtSusu.setText("0");

        txtFanta.setText("0");

        txtJeruk.setText("0");

        cbFanta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFantaActionPerformed(evt);
            }
        });

        cbJeruk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJerukActionPerformed(evt);
            }
        });

        txtTotTeh.setText("0");

        txtTotSusu.setText("0");

        txtTotFanta.setText("0");

        txtTotJeruk.setText("0");

        btnTotalMakanan.setText("Total");
        btnTotalMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalMakananActionPerformed(evt);
            }
        });

        txtTotal.setText("0");

        btnMenuUtama.setText("Kembali ke Menu Utama");
        btnMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUtamaActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(294, 294, 294)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnReset)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkTeh)
                                    .addComponent(chkSusu)
                                    .addComponent(chkFanta)
                                    .addComponent(chkJeruk)))
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtJeruk, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(txtFanta, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSusu, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTeh, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbTeh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbSusu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbFanta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbJeruk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(btnTotalMakanan)))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotTeh, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(txtTotSusu)
                    .addComponent(txtTotFanta)
                    .addComponent(txtTotJeruk)
                    .addComponent(txtTotal))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMenuUtama)
                .addGap(319, 319, 319))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTeh)
                    .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSusu)
                    .addComponent(cbSusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotSusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFanta)
                    .addComponent(txtFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkJeruk)
                    .addComponent(txtJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalMakanan)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addGap(56, 56, 56)
                .addComponent(btnMenuUtama)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehActionPerformed
        int jumlah = (int)cbTeh.getSelectedIndex();
        double harga = Double.parseDouble(txtTeh.getText());
        double total = jumlah*harga;
        txtTotTeh.setText(Double.toString(total));
    }//GEN-LAST:event_cbTehActionPerformed

    private void chkTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTehActionPerformed
        txtTeh.setText("5000");
    }//GEN-LAST:event_chkTehActionPerformed

    private void chkSusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSusuActionPerformed
       txtSusu.setText("7000");
    }//GEN-LAST:event_chkSusuActionPerformed

    private void chkFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFantaActionPerformed
        txtFanta.setText("6000");
    }//GEN-LAST:event_chkFantaActionPerformed

    private void chkJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJerukActionPerformed
        txtJeruk.setText("10000");
    }//GEN-LAST:event_chkJerukActionPerformed

    private void cbSusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSusuActionPerformed
       int jumlah = (int) cbSusu.getSelectedIndex();
       double harga = Double.parseDouble(txtSusu.getText());
       double total = jumlah*harga;
       txtTotSusu.setText(Double.toString(total));
    }//GEN-LAST:event_cbSusuActionPerformed

    private void cbFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFantaActionPerformed
        int jumlah = (int) cbFanta.getSelectedIndex();
        double harga = Double.parseDouble(txtFanta.getText());
        double total = jumlah*harga;
        txtTotFanta.setText(Double.toString(total));
    }//GEN-LAST:event_cbFantaActionPerformed

    private void cbJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJerukActionPerformed
        int jumlah = (int) cbJeruk.getSelectedIndex();
        double harga = Double.parseDouble(txtJeruk.getText());
        double total = jumlah*harga;
        txtTotJeruk.setText(Double.toString(total));
    }//GEN-LAST:event_cbJerukActionPerformed

    private void btnTotalMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalMakananActionPerformed
        double teh = Double.parseDouble(txtTotTeh.getText());
        double susu = Double.parseDouble(txtTotSusu.getText());
        double fanta = Double.parseDouble(txtTotFanta.getText());
        double jeruk = Double.parseDouble(txtTotJeruk.getText());
        double total = teh + susu + fanta + jeruk;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalMakananActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtTeh.setText("0");
        txtSusu.setText("0");
        txtFanta.setText("0");
        txtJeruk.setText("0");
        cbTeh.setSelectedIndex(0);
        cbSusu.setSelectedIndex(0);
        cbFanta.setSelectedIndex(0);
        cbJeruk.setSelectedIndex(0);
        chkTeh.setSelected(false);
        chkSusu.setSelected(false);
        chkFanta.setSelected(false);
        chkJeruk.setSelected(false);
        txtTotal.setText("0");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUtamaActionPerformed
      String total = txtTotal.getText();
      utama.setTotalMinuman(total);
      this.dispose();
    }//GEN-LAST:event_btnMenuUtamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuUtama;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotalMakanan;
    private javax.swing.JComboBox<String> cbFanta;
    private javax.swing.JComboBox<String> cbJeruk;
    private javax.swing.JComboBox<String> cbSusu;
    private javax.swing.JComboBox<String> cbTeh;
    private javax.swing.JCheckBox chkFanta;
    private javax.swing.JCheckBox chkJeruk;
    private javax.swing.JCheckBox chkSusu;
    private javax.swing.JCheckBox chkTeh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtFanta;
    private javax.swing.JTextField txtJeruk;
    private javax.swing.JTextField txtSusu;
    private javax.swing.JTextField txtTeh;
    private javax.swing.JTextField txtTotFanta;
    private javax.swing.JTextField txtTotJeruk;
    private javax.swing.JTextField txtTotSusu;
    private javax.swing.JTextField txtTotTeh;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
