/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas12062025;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PembayaranTokooo extends javax.swing.JFrame {

    /**
     * Creates new form PembayaranTokooo
     */
    public PembayaranTokooo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelJumlah = new javax.swing.JLabel();
        labelPembelian = new javax.swing.JLabel();
        labelDiskon = new javax.swing.JLabel();
        labelPembayaran = new javax.swing.JLabel();
        cbBarang = new javax.swing.JComboBox<>();
        labelHarga = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        txtTotBeli = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        txtTotBayar = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnHitungKembalian = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        labelUangPembayaran = new javax.swing.JLabel();
        labelUangKembali = new javax.swing.JLabel();
        txtUang = new javax.swing.JTextField();
        txtSisa = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();
        labelBayar = new javax.swing.JLabel();
        cbBayar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelJudul.setText("MINIMARKET DITA");

        labelNama.setText("Nama barang");

        labelJumlah.setText("Jumlah");

        labelPembelian.setText("Total Pembelian");

        labelDiskon.setText("Diskon");

        labelPembayaran.setText("Total Pembayaran");

        cbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih barang", "Susu", "Permen", "Mie instant", "Roti" }));
        cbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBarangActionPerformed(evt);
            }
        });

        labelHarga.setText("Harga");

        txtTotBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotBeliActionPerformed(evt);
            }
        });

        txtDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiskonActionPerformed(evt);
            }
        });

        txtTotBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotBayarActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnHitungKembalian.setText("Hitung Kembalian");
        btnHitungKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungKembalianActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        labelUangPembayaran.setText("Uang Pembayaran");

        labelUangKembali.setText("Uang Kembalian");

        txtUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        labelBayar.setText("Metode Pembayaran");

        cbBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pembayaran", "Cash", "Qris", "Kredit", " " }));
        cbBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBayarActionPerformed(evt);
            }
        });

        area1.setColumns(20);
        area1.setRows(2);
        area1.setTabSize(2);
        jScrollPane1.setViewportView(area1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelJudul)
                .addGap(321, 321, 321))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBayar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelJumlah)
                                    .addComponent(labelNama)
                                    .addComponent(labelPembelian)
                                    .addComponent(labelPembayaran)
                                    .addComponent(labelUangPembayaran)
                                    .addComponent(labelUangKembali))
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtJumlah)
                                        .addComponent(txtTotBeli)
                                        .addComponent(txtDiskon, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTotBayar))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHitungKembalian)
                            .addComponent(btnHitung)
                            .addComponent(btnReset)
                            .addComponent(btnKeluar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(514, Short.MAX_VALUE)
                        .addComponent(labelHarga)
                        .addGap(67, 67, 67)
                        .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPembelian)
                    .addComponent(txtTotBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitungKembalian))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(labelPembayaran))
                        .addComponent(btnReset))
                    .addComponent(txtTotBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelBayar))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUangPembayaran))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUangKembali)
                    .addComponent(txtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try{
        int harga = Integer.parseInt(txtHarga.getText());
        int jumlah = Integer.parseInt(txtJumlah.getText());
        int total = harga*jumlah;
        txtTotBeli.setText(Integer.toString(total));
        double diskon = 0;
        if(total>100000)
            diskon = 0.1*total;
        
        double tbayar = total - diskon;
        txtDiskon.setText(Double.toString(diskon));
        txtTotBayar.setText(Double.toString(tbayar));
        cbBayar.requestFocusInWindow();
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this, "Masukan angka valid", "Jumlah error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtTotBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotBeliActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiskonActionPerformed

    private void txtTotBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotBayarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtHarga.setText("");
       txtJumlah.setText("");
       txtTotBeli.setText("");
       txtDiskon.setText("");
       txtTotBayar.setText("");
       txtUang.setText("");
       txtSisa.setText("");
       cbBarang.setSelectedIndex(0);
       cbBayar.setSelectedIndex(0);
       cbBarang.requestFocusInWindow();
    }//GEN-LAST:event_btnResetActionPerformed

    private void cbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBarangActionPerformed
        
        int brg = (int) cbBarang.getSelectedIndex();
        switch(brg){
            case 1 : txtHarga.setText("100000");break;
            case 2 : txtHarga.setText("5000");break;
            case 3 : txtHarga.setText("10000");break;
            case 4 : txtHarga.setText("20000");break;
        }
        txtJumlah.requestFocusInWindow();
        
         
    }//GEN-LAST:event_cbBarangActionPerformed

    private void btnHitungKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungKembalianActionPerformed
        try{
        double uang = Double.parseDouble(txtUang.getText());
        double total = Double.parseDouble(txtTotBayar.getText());
        
        
        if(uang < total)
            JOptionPane.showMessageDialog(this, "Uang pembayaran Kurang","WARNING",JOptionPane.INFORMATION_MESSAGE);
        else
        {
            Double kembalian = uang-total;
            txtSisa.setText(Double.toString(kembalian));
        }
       
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Masukan angka yang valid","Uang Pembayaran Error", JOptionPane.ERROR_MESSAGE);
        }
        area1.setEditable(false);
        area1.append("Terima Kasih Telah Berbelanja di Toko Kami.");
    
       
        
    }//GEN-LAST:event_btnHitungKembalianActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar", "Peringatan", JOptionPane.YES_NO_OPTION);
        if(pilihan == JOptionPane.YES_NO_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void cbBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBayarActionPerformed
        txtUang.requestFocusInWindow();
    }//GEN-LAST:event_cbBayarActionPerformed

    private void txtUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembayaranTokooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembayaranTokooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembayaranTokooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembayaranTokooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembayaranTokooo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitungKembalian;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbBarang;
    private javax.swing.JComboBox<String> cbBayar;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBayar;
    private javax.swing.JLabel labelDiskon;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPembayaran;
    private javax.swing.JLabel labelPembelian;
    private javax.swing.JLabel labelUangKembali;
    private javax.swing.JLabel labelUangPembayaran;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtSisa;
    private javax.swing.JTextField txtTotBayar;
    private javax.swing.JTextField txtTotBeli;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
